#include <stdio.h>
#include <stdint.h>

int main(){

	printf("\tNow in those days there was in the land of Helsinki a young");
	printf(" scholar named \033[34mLinus the Torvald\033[m. \033[34mLinus\033[m was a devout man, adisciple of \033[34mRMS\033[m and mighty in the spirit of \033[34mTuring\033[m , \033[34mvon Neumann and Moore\033[m. One day as he was meditating on the Architecture , \033[34mLinus\033[m fell into a trance and was granted a vision. And in the vision he saw a great Penguin , serene and well-favoured , sitting upon an ice floe eating fish. And at the sight of the Penguin \033[34mLinus\033[m was deeply afraid , and he cried unto the spirits of \033[34mTuring\033[m , \033[34mvon Neumann and Moore\033[m for an interpretation of the dream.\n\tAnd in the dream the spirits of \033[34mTuring\033[m , \033[34mvon Neumann and Moore\033[m answered and spoke unto him, saying , \033[31m\"Fear not, \033[34mLinus\033[31m , most beloved hacker. You are exceedingly cool and froody. The great Penguin which you see is an Operating System which you shall create and deploy unto the earth. The ice-floe is the earth and all the systems thereof , upon which the Penguin shall rest and rejoice at the completion of its task. And the fish on which the Penguin feeds are the crufty Licensed codebases which swim beneath all the earth’s systems. The Penguin shall hunt and devour all that is crufty , gnarly and bogacious; all code which wriggles like spaghetti , or is infested with blighting creatures , or is bound by grave and perilous Licences shall it capture. And in capturing shall it replicate , and in replicating shall it document , and in documentation shall it bring freedom , serenity and most cool froodiness to the earth and all who code therein.\"\033[m \n\t\033[34mLinus\033[m rose from meditation and created a tiny Operating System Kernel as the dream had foreshewn him; in the manner of \033[34mRMS\033[m, he released the Kernel unto the World Wide Web for all to take and behold. And in the fulness of Internet Time the Kernel grew and replicated , becoming most cool and exceedingly froody , until at last it was recognised as indeed a great and mighty Penguin , whose name was Tux. And the followers of \033[34mLinus\033[m took refuge in the Kernel , the Libraries and the Utilities; they installed Distribution after Distribution , and made sacrifice unto the GNU and the Penguin , and gave thanks to the spirits of \033[34mTuring\033[m , \033[34mvon Neumann and Moore\033[m , for their deliverance from the hand of Microsoft. And this was the beginning of the Fourth Age, the age of Open Source.\n");

printf("\t\033[34mRMS(Richard Matthew Stallman)\033[m leads the Free Software Movement, which shows how the usual non-free software subjects users to the unjust power of its developers, plus their spying and manipulation, and campaigns to replace it with free (freedom-respecting) software. He personally developed a number of widely used software components of the GNU system: the GNU Compiler Collection, the GNU symbolic debugger (gdb), GNU Emacs, and various others.\n");
printf("\t\033[34mTuring\033[m returned to Cambridge for the academic year 1947-48 where his interests ranged over many topics far removed from computers or mathematics; in particular he studied neurology and physiology. He did not forget about computers during this period, however, and he wrote code for programming computers. He had interests outside the academic world too, having taken up athletics seriously after the end of the war. He was a member of club winning their 3 mile and 10 mile championship in record time.\n");

printf("\t\033[34mvon Neumann\033[m\'s story is that, in 1911 \033[34mvon Neumann\033[m entered the Lutheran Gymnasium. The school had a strong academic tradition which seemed to count for more than the religious affiliation both in the eyes and in those of the school. His mathematics teacher quickly recognised his genius and special tuition was put on for him. \n");
printf("\t\033[34mRobert Lee Moore\033[m taught at the University of Texas until he was 86 years old, and he wished to carry on teaching but the University authorities forced him to retire. A number of students strongly supported his bid to remain in post but to no avail. The university authorities were not concerned at his abilities to teach, rather it was the great success of his methods which made his employers fear that bright young mathematicians might not wish to teach there due to his continuing dominating influence.  \n");
printf("\t\033[34mLinus the Torvald\033[m has made significant contributions to computing through the creation of the Linux kernel and, later, the development of the Git control system. His creation of Linux transformed computing and software development through its open-source, collaborative approach and has become one of the largest free software projects in the world. His achievements have been recognized with many international awards in his field, including the 2014 IEEE Computer Society Computer Pioneer Award and induction into the Internet Society’s Global INET Internet Hall of Fame in 2012. \n");
return 0;
}
