.IGNORE:
all:

	gcc hw0303.c -o hw0303 -lm
	gcc -o hw0301  mycircle.c hw0301.c -lm
	gcc hw0305.c diceRolls.c -o hw0305 `pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`
	gcc -o hw0304-1 hw0304.c hw0304-1.c -lm
	gcc -o hw0304-2 hw0304.c hw0304-2.c -lm
	gcc -o hw0302 mycontrol.c hw0302.c -lm
	

