.IGNORE:
all:

	gcc -o hw0501  hw0501.c mystatistics.c -lm
	gcc -o hw0503 hw0503.c mysphere.c -lm
	gcc -o hw0502 hw0502.c myge.c -lm
	gcc -o hw0504 hw0504.c mytlv.c -lm
	gcc -o hw0505 hw0505.c tas.c decode.c -lm
